services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_API_USER}
      DB_PASSWORD: ${DB_API_PASSWORD}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_WORKER_USER}
      DB_PASSWORD: ${DB_WORKER_PASSWORD}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
