services:
  warframe_watcher:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - NGROK_AUTHTOKEN=3BAI4dDCrUf2n80aMzbQYjEIiBI_ap5qMCHBeLsQC7t5k3M9
      - NGROK_API_URL=https://api.ngrok.com
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    stdin_open: true
    tty: true
