FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

FROM node:18-alpine AS runtime
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000

CMD ["node", "src/server.js"]