FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

FROM node:18-alpine AS runtime
WORKDIR /app
COPY --from=builder /app /app

CMD ["node", "src/worker/dataWorker.js"]