CREATE SCHEMA IF NOT EXISTS wfdata;

GRANT USAGE ON SCHEMA wfdata TO worker;
GRANT USAGE ON SCHEMA wfdata TO api;

ALTER DEFAULT PRIVILEGES IN SCHEMA wfdata
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO worker;

ALTER DEFAULT PRIVILEGES IN SCHEMA wfdata
GRANT SELECT ON TABLES TO api;