    CREATE SCHEMA IF NOT EXISTS app_data;

    GRANT USAGE ON SCHEMA app_data TO worker;
    GRANT USAGE ON SCHEMA app_data TO api;

    ALTER DEFAULT PRIVILEGES IN SCHEMA app_data
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO worker;

    ALTER DEFAULT PRIVILEGES IN SCHEMA app_data
    GRANT SELECT ON TABLES TO api;